export const erc20Abi = [
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
] as const;

export const commitmentEscrowAbi = [
  {
    type: "function",
    name: "createReservation",
    stateMutability: "nonpayable",
    inputs: [
      { name: "customer", type: "address" },
      { name: "providerCommitment", type: "uint128" },
      { name: "customerCommitment", type: "uint128" },
      { name: "providerCompensation", type: "uint128" },
      { name: "startTime", type: "uint64" },
      { name: "freeCancellationDeadline", type: "uint64" },
      { name: "gracePeriod", type: "uint64" },
      { name: "disputeWindow", type: "uint64" },
      { name: "metadataHash", type: "bytes32" },
    ],
    outputs: [{ name: "reservationId", type: "uint256" }],
  },
  {
    type: "function",
    name: "acceptReservation",
    stateMutability: "nonpayable",
    inputs: [{ name: "reservationId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "cancelReservation",
    stateMutability: "nonpayable",
    inputs: [{ name: "reservationId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "expireUnacceptedReservation",
    stateMutability: "nonpayable",
    inputs: [{ name: "reservationId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "confirmAttendance",
    stateMutability: "nonpayable",
    inputs: [{ name: "reservationId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "openNoShowClaim",
    stateMutability: "nonpayable",
    inputs: [
      { name: "reservationId", type: "uint256" },
      { name: "outcome", type: "uint8" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "disputeClaim",
    stateMutability: "nonpayable",
    inputs: [{ name: "reservationId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "finalizeUndisputedClaim",
    stateMutability: "nonpayable",
    inputs: [{ name: "reservationId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "getReservation",
    stateMutability: "view",
    inputs: [{ name: "reservationId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "provider", type: "address" },
          { name: "customer", type: "address" },
          { name: "providerCommitment", type: "uint128" },
          { name: "customerCommitment", type: "uint128" },
          { name: "providerCompensation", type: "uint128" },
          { name: "startTime", type: "uint64" },
          { name: "freeCancellationDeadline", type: "uint64" },
          { name: "gracePeriod", type: "uint64" },
          { name: "disputeWindow", type: "uint64" },
          { name: "claimOpenedAt", type: "uint64" },
          { name: "status", type: "uint8" },
          { name: "pendingOutcome", type: "uint8" },
          { name: "finalOutcome", type: "uint8" },
          { name: "providerConfirmed", type: "bool" },
          { name: "customerConfirmed", type: "bool" },
          { name: "metadataHash", type: "bytes32" },
        ],
      },
    ],
  },
] as const;
